/** The Pilot's acts: prologue, three procedural acts, epilogue. */
import type { ActDef, BiomeDef, Weighted } from '../../../engine/types';
import { LINES } from './dialogue';
import { C35_COMBAT, CUSTOMS_COMBAT, CUSTOMS_QUEUES, SCHOOL_COMBAT } from './rooms';

const RICK = { gadget: 'freeze-ray', entrance: 'walk' } as const;
const w = (id: string, weight: number): Weighted => ({ id, weight });

export const SMITH_NIGHT: BiomeDef = {
  id: 'smith-house-night',
  name: 'The Smith House (night)',
  palette: {
    background: 0x0f0d1a,
    floor: 0x6f5b4a,
    floorAlt: 0x5d4b3c,
    wall: 0x3b3552,
    wallTop: 0x524a70,
    block: 0x7a5c3e,
    blockTop: 0x98754f,
    cliff: 0x333344,
    cliffShadow: 0x222233,
    slow: 0x5a7fbf,
    accent: 0x97ce4c,
    door: 0x8a6d4b,
  },
  floorPattern: 'planks',
  music: 'calm',
};

export const SCHOOL_BIOME: BiomeDef = {
  id: 'harry-herpson-high',
  name: 'Harry Herpson High',
  palette: {
    background: 0x1d1a2b,
    floor: 0xd9d2bf,
    floorAlt: 0xc2b99f,
    wall: 0x5b7fa3,
    wallTop: 0x7ea3c7,
    block: 0xa0714a,
    blockTop: 0xc9935f,
    cliff: 0x444444,
    cliffShadow: 0x222222,
    slow: 0x9bd35a,
    accent: 0xf2c14e,
    door: 0x8a6d4b,
  },
  floorPattern: 'checker',
  music: 'school',
};

export const C35_BIOME: BiomeDef = {
  id: 'dimension-35c',
  name: 'Dimension 35-C',
  palette: {
    background: 0x16262a,
    floor: 0x9fe0b5,
    floorAlt: 0x7fcf9e,
    wall: 0x8b5fbf,
    wallTop: 0xb48be0,
    block: 0xd98f6b,
    blockTop: 0xf2b08f,
    cliff: 0x6a5acd,
    cliffShadow: 0x3b2f6b,
    slow: 0xf28fb8,
    accent: 0xffd54a,
    door: 0x6a4c93,
  },
  floorPattern: 'blobs',
  music: '35c',
};

export const CUSTOMS_BIOME: BiomeDef = {
  id: 'interdimensional-customs',
  name: 'Interdimensional Customs',
  palette: {
    background: 0x10131c,
    floor: 0xc9ced9,
    floorAlt: 0xb3b9c7,
    wall: 0x3d4a5c,
    wallTop: 0x56657a,
    block: 0x6b7a8f,
    blockTop: 0x8c9bb0,
    cliff: 0x333344,
    cliffShadow: 0x222233,
    slow: 0x8fd3ff,
    accent: 0x6fd0ff,
    door: 0x2f6f8f,
  },
  floorPattern: 'grid',
  music: 'customs',
};

export const SMITH_DAY: BiomeDef = {
  id: 'smith-house-day',
  name: 'The Smith House',
  palette: {
    background: 0x2a2233,
    floor: 0xc9a27a,
    floorAlt: 0xb08a63,
    wall: 0xb08a5a,
    wallTop: 0xe0c38c,
    block: 0x7f9fd0,
    blockTop: 0x9fbfe8,
    cliff: 0x444444,
    cliffShadow: 0x222222,
    slow: 0x9fd8f0,
    accent: 0x97ce4c,
    door: 0x8a6d4b,
  },
  floorPattern: 'planks',
  music: 'garage',
};

export const PROLOGUE: ActDef = {
  id: 'pilot-prologue',
  name: 'Just a Test',
  subtitle: 'Prologue',
  playable: 'morty',
  biome: SMITH_NIGHT,
  layout: {
    kind: 'fixed',
    start: { x: 0, y: 0 },
    rooms: [
      { x: 0, y: 0, kind: 'start', template: 'pilot-bedroom', script: 'pilot-bedroom' },
      { x: 1, y: 0, kind: 'combat', template: 'pilot-garage', script: 'pilot-garage' },
      { x: 2, y: 0, kind: 'finale', template: 'pilot-cockpit' },
    ],
  },
  enemyPool: [w('junk-drone', 1)],
  itemPool: [],
  eliteChance: 0,
  finale: [{ kind: 'encounter', encounter: 'pilot-bomb-defuse' }],
  // Handed over by the garage script when target practice starts.
  weapon: { item: 'garage-junk', when: 'scripted', from: 'rick', line: LINES.rick.targetPractice },
  rick: RICK,
  mechanics: [],
  intro: ['pilot-wake-up'],
  outro: ['pilot-breakfast'],
};

export const SCHOOL: ActDef = {
  id: 'pilot-school',
  name: 'Harry Herpson High',
  subtitle: 'Act 1',
  playable: 'morty',
  biome: SCHOOL_BIOME,
  layout: {
    kind: 'procedural',
    roomCount: [8, 11],
    templates: SCHOOL_COMBAT.map((t) => t.id),
    startTemplate: 'school-start',
    treasureTemplate: 'school-treasure',
    shopTemplate: 'school-shop',
  },
  enemyPool: [w('pop-quiz', 4), w('hall-monitor', 2), w('dodgeball-jock', 3), w('cafeteria-slop', 3), w('pep-squad', 2), w('lab-partner', 2)],
  itemPool: [
    w('freeze-ray-mod', 2),
    w('ricks-flask', 3),
    w('neutrino-bomb', 1),
    w('dodgeball', 3),
    w('hall-pass', 3),
    w('chemistry-set', 3),
    w('calculator', 3),
    w('letterman-jacket', 3),
    w('detention-slip', 2),
    w('mystery-meat', 3),
    w('broken-leg-serum', 1),
    w('travel-pillow', 1),
    w('mega-seed', 1),
    w('burp-canister', 1),
    w('junk-magnet', 1),
  ],
  eliteChance: 0.12,
  hazards: [w('burst-locker', 2), w('slop-spill', 1)],
  hazardChance: 0.5,
  shop: { keeperArt: 'vending-machine', name: 'Vending Machine', alwaysStocks: ['mystery-meat'] },
  specialRoom: 'pilot-pop-quiz',
  finale: [{ kind: 'boss', boss: 'frank-palicky', template: 'school-boss' }],
  weapon: { item: 'gym-bag-dodgeballs', when: 'start', from: 'morty', line: LINES.morty.gymBag },
  rick: RICK,
  mechanics: [],
  startStatuses: ['sleep-deprived'],
  intro: ['pilot-school-intro'],
  outro: ['pilot-frank-shatter', 'pilot-principal'],
  exitLabel: 'Leave school with Rick',
};

export const DIMENSION_35C: ActDef = {
  id: 'pilot-35c',
  name: 'Dimension 35-C',
  subtitle: 'Act 2',
  playable: 'morty',
  biome: C35_BIOME,
  layout: {
    kind: 'procedural',
    roomCount: [8, 11],
    templates: C35_COMBAT.map((t) => t.id),
    startTemplate: '35c-start',
    treasureTemplate: '35c-treasure',
    shopTemplate: '35c-shop',
  },
  enemyPool: [w('gloop-hopper', 3), w('fruit-snatcher', 2), w('bonk-bloat', 2), w('puff-polyp', 3), w('bloom-tender', 2), w('brood-mound', 1), w('goo-slug', 2)],
  itemPool: [
    w('freeze-ray-mod', 2),
    w('ricks-flask', 2),
    w('neutrino-bomb', 2),
    w('hopper-legs', 3),
    w('shoe-battery-pack', 3),
    w('mega-fruit-smoothie', 3),
    w('broken-leg-serum', 3),
    w('spore-sack', 2),
    w('calculator', 1),
    w('letterman-jacket', 1),
    w('travel-pillow', 2),
    w('mega-seed', 1),
    w('burp-canister', 2),
    w('junk-magnet', 1),
  ],
  eliteChance: 0.15,
  hazards: [w('crumbling-ledge', 1)],
  hazardChance: 0.6,
  shop: { keeperArt: 'trader-critter', name: 'Trader Critter', alwaysStocks: ['broken-leg-serum'] },
  specialRoom: 'pilot-mega-grove',
  finale: [{ kind: 'encounter', encounter: 'pilot-big-mega-tree' }],
  weapon: { item: 'ricks-spare-ray-gun', when: 'start', from: 'rick', line: LINES.rick.spareGun },
  rick: RICK,
  mechanics: ['grappling-shoes'],
  intro: ['pilot-35c-arrival'],
  outro: ['pilot-35c-outro'],
  exitArt: 'exit-transit',
  exitLabel: 'Take the transit gate to Customs',
};

export const CUSTOMS: ActDef = {
  id: 'pilot-customs',
  name: 'Interdimensional Customs',
  subtitle: 'Act 3',
  playable: 'morty',
  biome: CUSTOMS_BIOME,
  layout: {
    kind: 'procedural',
    // Start + 3-4 queue rooms + these keeps Customs within 8-12 rooms like the other acts.
    roomCount: [6, 7],
    templates: CUSTOMS_COMBAT.map((t) => t.id),
    startTemplate: 'customs-start',
    treasureTemplate: 'customs-treasure',
    shopTemplate: 'customs-shop',
    calmPrefix: { count: [3, 4], templates: CUSTOMS_QUEUES.map((t) => t.id), lastTemplate: 'customs-checkpoint' },
  },
  enemyPool: [
    w('gromflomite-clerk', 3),
    w('gromflomite-guard', 3),
    w('gromflomite-riot', 2),
    w('gromflomite-sniper', 2),
    w('gromflomite-courier', 3),
    w('gromflomite-notary', 2),
    w('gromflomite-dispatcher', 1),
  ],
  itemPool: [
    w('freeze-ray-mod', 2),
    w('neutrino-bomb', 2),
    w('customs-stamp', 3),
    w('red-tape', 2),
    w('duty-free-cologne', 3),
    w('contraband-blaster', 2),
    w('travel-pillow', 3),
    w('ricks-flask', 2),
    w('mystery-meat', 1),
    w('hall-pass', 1),
    w('detention-slip', 1),
    w('mega-seed', 1),
    w('burp-canister', 1),
    w('junk-magnet', 1),
  ],
  eliteChance: 0.15,
  hazards: [w('scanner-sweeper', 1)],
  hazardChance: 0.45,
  shop: { keeperArt: 'duty-free-kiosk', name: 'Duty-Free', priceMult: 1.35, alwaysStocks: ['travel-pillow'] },
  specialRoom: 'pilot-confiscated-vault',
  finale: [
    { kind: 'boss', boss: 'customs-supervisor', template: 'customs-boss' },
    { kind: 'encounter', encounter: 'pilot-customs-escape' },
  ],
  // Canon: Rick hands over his own gun when their cover is blown (the suspicion mechanic).
  weapon: { item: 'ricks-ray-gun', when: 'scripted', from: 'rick', line: LINES.rick.takeMyGun },
  rick: RICK,
  mechanics: ['suspicion'],
  intro: ['pilot-customs-intro'],
  outro: ['pilot-customs-outro'],
  exitLabel: 'Into the departure hall',
};

export const EPILOGUE: ActDef = {
  id: 'pilot-epilogue',
  name: 'Temporarily a Genius',
  subtitle: 'Epilogue',
  playable: 'morty',
  biome: SMITH_DAY,
  layout: { kind: 'fixed', start: { x: 0, y: 0 }, rooms: [{ x: 0, y: 0, kind: 'finale', template: 'pilot-living-room' }] },
  enemyPool: [],
  itemPool: [],
  eliteChance: 0,
  finale: [{ kind: 'encounter', encounter: 'pilot-epilogue' }],
  // Home again: Rick took his gun back on the way through the portal.
  unarmed: true,
  rick: RICK,
  mechanics: [],
};
